server:
  port: 8081

spring:
  application:
    name: smart-link-platform
  datasource:
    url: jdbc:postgresql://localhost:5435/smart_platform_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect