server:
  port: 8081

spring:
  application:
    name: smart-link-platform

  datasource:
    url: jdbc:postgresql://postgres:5432/smart_platform_db
    username: postgres
    password: 1234

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    com.mm: debug
  file:
    name: logs/app.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ALWAYS

link:
  expiration-days: 3

info:
  app:
    name: Smart Link Platform
    description: URL shortener with analytics
    version: 1.0.0